# Generated by Django 3.2.9 on 2022-01-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npuname', models.CharField(max_length=50)),
                ('npnots', models.TextField()),
                ('date', models.DateField(blank='true')),
                ('time', models.TimeField(blank='true')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mobileno', models.TextField()),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('nikename', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
