# Generated by Django 3.2.9 on 2022-01-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
